version: "3"
services:
   frontend:
       container_name: fireworkFE
       image: ghcr.io/firework-01-92-99/firework:dev
       ports: 
          - "8080:80"
       networks:
         NETWORK:
            ipv4_address: 172.21.0.11
networks:
  default:
    external:
       name: firework
  NETWORK:
    external: true
