version: "3"
services:
   frontend:
       container_name: ppclothesFE
       build: 
          context: .
       image: frontend
       ports: 
          - "8080:80"
       networks:
         NETWORK:
            ipv4_address: 172.21.0.11
networks:
  default:
    external:
       name: NETWORK
  NETWORK:
    external: true
