version: "3"
services:
  frontend:
    build: .
    image: frontend
    ports:
      - "8080:80"
    container_name: fireworkFE
    networks:
       NETWORK:
          ipv4_address: 172.21.0.11
networks:
  default:
    external:
       name: NETWORK
  NETWORK:
    external: true