name: client
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/firework-01-92-99/firework:dev

  deploy:
    needs:
      - build
    runs-on: ubuntu-20.04
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          # port: ${{ secrets.SERVERPORT }}
          script: |
            cd ~/project/backend
            docker-compose down
            docker-compose pull
            docker-compose up -d
            docker image prune -af


